require('dotenv').config();
const express=require('express');const path=require('path');const cors=require('cors');const helmet=require('helmet');const rateLimit=require('express-rate-limit');const mongoose=require('mongoose');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');
const app=express();app.use(helmet({crossOriginResourcePolicy:false}));app.use(cors());app.use(express.json({limit:'4mb'}));
const customerDir=path.join(__dirname,'..','customer'),managerDir=path.join(__dirname,'..','manager');
app.use('/manager',express.static(managerDir));app.use('/customer',express.static(customerDir));app.use(express.static(customerDir));app.get('/',(req,res)=>res.sendFile(path.join(customerDir,'index.html')));
const serviceSchema=new mongoose.Schema({title:{type:String,required:true,trim:true},description:{type:String,default:''},icon:{type:String,default:'✦'},features:[String],startingPrice:{type:Number,default:0},timeline:String,active:{type:Boolean,default:true},order:{type:Number,default:0}},{timestamps:true});
const portfolioSchema=new mongoose.Schema({title:{type:String,required:true,trim:true},description:String,category:{type:String,default:'Project'},client:String,technologies:[String],projectUrl:String,githubUrl:String,featured:{type:Boolean,default:false},active:{type:Boolean,default:true},order:{type:Number,default:0},media:[String],results:[String]},{timestamps:true});
const leadSchema=new mongoose.Schema({enquiryId:{type:String,unique:true,index:true},name:{type:String,required:true},company:String,email:{type:String,required:true},whatsapp:String,projectType:String,budget:String,deadline:String,referenceUrl:String,requirements:{type:String,required:true},status:{type:String,default:'New'},notes:String,customer:{type:mongoose.Schema.Types.ObjectId,ref:'Customer'}},{timestamps:true});
const testimonialSchema=new mongoose.Schema({name:String,company:String,role:String,quote:String,rating:{type:Number,default:5},avatar:String,approved:{type:Boolean,default:false},order:Number},{timestamps:true});
const faqSchema=new mongoose.Schema({question:String,answer:String,active:{type:Boolean,default:true},order:Number},{timestamps:true});
const bannerSchema=new mongoose.Schema({eyebrow:String,title:String,text:String,ctaText:String,ctaUrl:String,image:String,active:{type:Boolean,default:true},order:Number},{timestamps:true});
const siteSchema=new mongoose.Schema({key:{type:String,unique:true},heroTitle:String,heroText:String,footerText:String,email:String,whatsapp:String,phone:String,instagram:String,linkedin:String,youtube:String,github:String,announcement:String},{timestamps:true});
const managerSchema=new mongoose.Schema({username:{type:String,unique:true,lowercase:true,trim:true},passwordHash:String,role:{type:String,default:'manager'},active:{type:Boolean,default:true},lastLoginAt:Date},{timestamps:true});
const customerSchema=new mongoose.Schema({name:{type:String,required:true,trim:true},email:{type:String,required:true,unique:true,lowercase:true,trim:true},phone:String,company:String,passwordHash:{type:String,required:true},active:{type:Boolean,default:true},lastLoginAt:Date},{timestamps:true});
const projectSchema=new mongoose.Schema({projectId:{type:String,unique:true,index:true},customer:{type:mongoose.Schema.Types.ObjectId,ref:'Customer'},name:String,description:String,status:{type:String,default:'Planning'},progress:{type:Number,default:0,min:0,max:100},value:{type:Number,default:0},startDate:Date,dueDate:Date,notes:String},{timestamps:true});
const quoteSchema=new mongoose.Schema({quoteId:{type:String,unique:true,index:true},customer:{type:mongoose.Schema.Types.ObjectId,ref:'Customer'},project:{type:mongoose.Schema.Types.ObjectId,ref:'Project'},items:[{name:String,quantity:Number,price:Number}],discount:{type:Number,default:0},gst:{type:Number,default:18},subtotal:Number,total:Number,status:{type:String,default:'DRAFT'},validUntil:Date},{timestamps:true});
const invoiceSchema=new mongoose.Schema({invoiceId:{type:String,unique:true,index:true},customer:{type:mongoose.Schema.Types.ObjectId,ref:'Customer'},project:{type:mongoose.Schema.Types.ObjectId,ref:'Project'},items:[{name:String,quantity:Number,price:Number}],subtotal:Number,gst:{type:Number,default:18},total:Number,status:{type:String,default:'UNPAID'},dueDate:Date},{timestamps:true});
const paymentSchema=new mongoose.Schema({transactionId:{type:String,index:true},customer:{type:mongoose.Schema.Types.ObjectId,ref:'Customer'},project:{type:mongoose.Schema.Types.ObjectId,ref:'Project'},amount:{type:Number,required:true},gateway:String,status:{type:String,default:'PENDING'},paidAt:Date},{timestamps:true});
const Service=mongoose.model('Service',serviceSchema),Portfolio=mongoose.model('Portfolio',portfolioSchema),Lead=mongoose.model('Lead',leadSchema),Testimonial=mongoose.model('Testimonial',testimonialSchema),FAQ=mongoose.model('FAQ',faqSchema),Banner=mongoose.model('Banner',bannerSchema),Site=mongoose.model('Site',siteSchema),Manager=mongoose.model('Manager',managerSchema),Customer=mongoose.model('Customer',customerSchema),Project=mongoose.model('Project',projectSchema),Quote=mongoose.model('Quote',quoteSchema),Invoice=mongoose.model('Invoice',invoiceSchema),Payment=mongoose.model('Payment',paymentSchema);
const loginLimiter=rateLimit({windowMs:15*60*1000,limit:20,standardHeaders:true,legacyHeaders:false});
function managerToken(m){return jwt.sign({sub:m._id.toString(),username:m.username,role:m.role,type:'manager'},process.env.MANAGER_JWT_SECRET,{expiresIn:process.env.MANAGER_JWT_EXPIRES||'30d'});}
function customerToken(c){return jwt.sign({sub:c._id.toString(),email:c.email,type:'customer'},process.env.CUSTOMER_JWT_SECRET||process.env.MANAGER_JWT_SECRET,{expiresIn:process.env.CUSTOMER_JWT_EXPIRES||'30d'});}
function auth(req,type){const token=(req.headers.authorization||'').startsWith('Bearer ')?req.headers.authorization.slice(7):null;if(!token)throw new Error('NO_TOKEN');const secret=type==='manager'?process.env.MANAGER_JWT_SECRET:(process.env.CUSTOMER_JWT_SECRET||process.env.MANAGER_JWT_SECRET);if(!secret)throw new Error('NO_SECRET');return jwt.verify(token,secret);}
function requireManager(req,res,next){try{req.auth=auth(req,'manager');if(req.auth.type!=='manager')throw new Error();next();}catch(e){res.status(401).json({message:'Manager session expired. Please sign in again.',code:'AUTH_REQUIRED'});}}
function requireCustomer(req,res,next){try{req.auth=auth(req,'customer');if(req.auth.type!=='customer')throw new Error();next();}catch(e){res.status(401).json({message:'Customer session expired. Please sign in again.',code:'AUTH_REQUIRED'});}}
function cleanArray(v){return Array.isArray(v)?v.map(x=>String(x).trim()).filter(Boolean):[];}function safeBody(b,fs){const o={};fs.forEach(f=>{if(b[f]!==undefined)o[f]=b[f]});return o;}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'creatarsh-api'}));
app.get('/api/public/content',async(req,res)=>{try{const [services,portfolio,testimonials,faqs,banners,site]=await Promise.all([Service.find({active:true}).sort({order:1}),Portfolio.find({active:true}).sort({order:1}),Testimonial.find({approved:true}).sort({order:1}),FAQ.find({active:true}).sort({order:1}),Banner.find({active:true}).sort({order:1}),Site.findOne({key:'main'})]);res.json({services,portfolio,testimonials,faqs,banners,site});}catch(e){res.status(500).json({message:'Failed to load website content'});}});
app.post('/api/public/leads',async(req,res)=>{try{const d=safeBody(req.body,['name','company','email','whatsapp','projectType','budget','deadline','referenceUrl','requirements']);if(!d.name||!d.email||!d.requirements)return res.status(400).json({message:'Name, email and requirements are required'});d.enquiryId='CR-'+Date.now().toString(36).toUpperCase();let customerId=null;try{const token=auth(req,'customer');if(token.type==='customer')customerId=token.sub}catch{}if(customerId)d.customer=customerId;const lead=await Lead.create(d);res.status(201).json({message:'Project brief received',enquiryId:lead.enquiryId});}catch(e){res.status(400).json({message:'Invalid lead data'});}});
app.post('/api/customer/register',loginLimiter,async(req,res)=>{try{const name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!name||!email||password.length<8)return res.status(400).json({message:'Name, email and an 8+ character password are required'});if(await Customer.findOne({email}))return res.status(409).json({message:'An account with this email already exists'});const c=await Customer.create({name,email,phone:String(req.body.phone||'').trim(),company:String(req.body.company||'').trim(),passwordHash:await bcrypt.hash(password,12)});res.status(201).json({token:customerToken(c),customer:{id:c._id,name:c.name,email:c.email,phone:c.phone,company:c.company}});}catch(e){res.status(400).json({message:'Could not create customer account'});}});
app.post('/api/customer/login',loginLimiter,async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');const c=await Customer.findOne({email,active:true});if(!c||!(await bcrypt.compare(password,c.passwordHash)))return res.status(401).json({message:'Invalid email or password'});c.lastLoginAt=new Date();await c.save();res.json({token:customerToken(c),customer:{id:c._id,name:c.name,email:c.email,phone:c.phone,company:c.company}});}catch(e){res.status(500).json({message:'Login service is unavailable'});}});
app.get('/api/customer/me',requireCustomer,async(req,res)=>{const c=await Customer.findById(req.auth.sub).select('-passwordHash');if(!c||!c.active)return res.status(401).json({message:'Customer account is inactive',code:'AUTH_REQUIRED'});res.json({customer:c});});
app.put('/api/customer/me',requireCustomer,async(req,res)=>{try{const d=safeBody(req.body,['name','phone','company']);const c=await Customer.findByIdAndUpdate(req.auth.sub,d,{new:true,runValidators:true}).select('-passwordHash');res.json({customer:c});}catch(e){res.status(400).json({message:'Could not update profile'});}});
app.get('/api/customer/projects',requireCustomer,async(req,res)=>res.json(await Project.find({customer:req.auth.sub}).sort({createdAt:-1})));
app.get('/api/customer/quotes',requireCustomer,async(req,res)=>res.json(await Quote.find({customer:req.auth.sub}).populate('project','name').sort({createdAt:-1})));
app.get('/api/customer/invoices',requireCustomer,async(req,res)=>res.json(await Invoice.find({customer:req.auth.sub}).populate('project','name').sort({createdAt:-1})));
app.get('/api/customer/payments',requireCustomer,async(req,res)=>res.json(await Payment.find({customer:req.auth.sub}).populate('project','name').sort({createdAt:-1})));
app.post('/api/manager/login',loginLimiter,async(req,res)=>{try{const username=String(req.body.username||'').trim().toLowerCase(),password=String(req.body.password||'');const m=await Manager.findOne({username,active:true});if(!m||!(await bcrypt.compare(password,m.passwordHash)))return res.status(401).json({message:'Invalid username or password'});m.lastLoginAt=new Date();await m.save();res.json({token:managerToken(m),manager:{username:m.username,role:m.role}});}catch(e){res.status(500).json({message:'Login service is unavailable'});}});
app.get('/api/manager/me',requireManager,async(req,res)=>{const m=await Manager.findById(req.auth.sub).select('username role active lastLoginAt');if(!m||!m.active)return res.status(401).json({message:'Manager account is inactive',code:'AUTH_REQUIRED'});res.json({manager:m});});
app.post('/api/manager/change-password',requireManager,async(req,res)=>{try{const m=await Manager.findById(req.auth.sub),current=String(req.body.currentPassword||''),next=String(req.body.newPassword||'');if(!m||!m.active)return res.status(401).json({message:'Manager account is inactive'});if(next.length<8)return res.status(400).json({message:'New password must be at least 8 characters'});if(!(await bcrypt.compare(current,m.passwordHash)))return res.status(401).json({message:'Current password is incorrect'});m.passwordHash=await bcrypt.hash(next,12);await m.save();res.json({message:'Password changed successfully'});}catch(e){res.status(500).json({message:'Could not change password'});}});
const resources={services:Service,portfolio:Portfolio,testimonials:Testimonial,faqs:FAQ,banners:Banner};const fields={services:['title','description','icon','features','startingPrice','timeline','active','order'],portfolio:['title','description','category','client','technologies','projectUrl','githubUrl','featured','active','order','media','results'],testimonials:['name','company','role','quote','rating','avatar','approved','order'],faqs:['question','answer','active','order'],banners:['eyebrow','title','text','ctaText','ctaUrl','image','active','order']};
for(const [name,Model] of Object.entries(resources)){app.get('/api/manager/'+name,requireManager,async(req,res)=>res.json(await Model.find().sort({order:1,createdAt:-1})));app.post('/api/manager/'+name,requireManager,async(req,res)=>{try{const d=safeBody(req.body,fields[name]);['features','technologies','media','results'].forEach(k=>{if(d[k]!==undefined)d[k]=cleanArray(d[k])});res.status(201).json(await Model.create(d));}catch(e){res.status(400).json({message:'Could not create item'});}});app.put('/api/manager/'+name+'/:id',requireManager,async(req,res)=>{try{const d=safeBody(req.body,fields[name]);['features','technologies','media','results'].forEach(k=>{if(d[k]!==undefined)d[k]=cleanArray(d[k])});const x=await Model.findByIdAndUpdate(req.params.id,d,{new:true,runValidators:true});if(!x)return res.status(404).json({message:'Item not found'});res.json(x);}catch(e){res.status(400).json({message:'Could not update item'});}});app.delete('/api/manager/'+name+'/:id',requireManager,async(req,res)=>{const x=await Model.findByIdAndDelete(req.params.id);if(!x)return res.status(404).json({message:'Item not found'});res.json({message:'Deleted'});});}
app.get('/api/manager/leads',requireManager,async(req,res)=>res.json(await Lead.find().populate('customer','name email company phone').sort({createdAt:-1})));app.put('/api/manager/leads/:id',requireManager,async(req,res)=>{const x=await Lead.findByIdAndUpdate(req.params.id,safeBody(req.body,['status','notes']),{new:true});if(!x)return res.status(404).json({message:'Lead not found'});res.json(x);});
app.get('/api/manager/site',requireManager,async(req,res)=>res.json(await Site.findOne({key:'main'})||{}));app.put('/api/manager/site',requireManager,async(req,res)=>{try{const d=safeBody(req.body,['heroTitle','heroText','footerText','email','whatsapp','phone','instagram','linkedin','youtube','github','announcement']);res.json(await Site.findOneAndUpdate({key:'main'},{$set:{...d,key:'main'}},{upsert:true,new:true,setDefaultsOnInsert:true}));}catch(e){res.status(400).json({message:'Could not save website content'});}});
app.get('/api/manager/customers',requireManager,async(req,res)=>res.json(await Customer.find().select('-passwordHash').sort({createdAt:-1})));app.get('/api/manager/projects',requireManager,async(req,res)=>res.json(await Project.find().populate('customer','name email company').sort({createdAt:-1})));app.get('/api/manager/quotes',requireManager,async(req,res)=>res.json(await Quote.find().populate('customer','name email company').sort({createdAt:-1})));app.get('/api/manager/invoices',requireManager,async(req,res)=>res.json(await Invoice.find().populate('customer','name email company').sort({createdAt:-1})));app.get('/api/manager/payments',requireManager,async(req,res)=>res.json(await Payment.find().populate('customer','name email company').sort({createdAt:-1})));
app.get('/api/manager/stats',requireManager,async(req,res)=>{const [portfolio,services,leads,customers,activeProjects,approvedTestimonials]=await Promise.all([Portfolio.countDocuments({active:true}),Service.countDocuments({active:true}),Lead.countDocuments(),Customer.countDocuments({active:true}),Project.countDocuments({status:{$nin:['Completed','Cancelled']}}),Testimonial.countDocuments({approved:true})]);res.json({portfolio,services,leads,customers,activeProjects,approvedTestimonials});});
async function seedInitialManager(){const u=String(process.env.MANAGER_INITIAL_USERNAME||'').trim().toLowerCase(),p=String(process.env.MANAGER_INITIAL_PASSWORD||'');if(!u||!p)return;if(p.length<8)throw new Error('MANAGER_INITIAL_PASSWORD must be at least 8 characters');if(!await Manager.findOne({username:u}))await Manager.create({username:u,passwordHash:await bcrypt.hash(p,12),role:'manager'});}
async function seedSite(){if(!await Site.findOne({key:'main'}))await Site.create({key:'main',heroTitle:'We build digital systems that move businesses forward.',heroText:'Creatarsh designs and develops modern websites, applications, business systems, automation and AI-powered products.',footerText:'Digital Systems & Development'});}
const port=process.env.PORT||5000;async function start(){if(process.env.MONGODB_URI){try{await mongoose.connect(process.env.MONGODB_URI);console.log('MongoDB connected');await seedInitialManager();await seedSite();}catch(e){console.error('MongoDB connection failed:',e.message);}}else console.log('No MONGODB_URI configured; demo mode.');app.listen(port,()=>console.log('Creatarsh API running on '+port));}start();
