const API=(window.CREATARSH_API_URL||localStorage.getItem('creatarsh_api_url')||((location.hostname==='localhost'||location.hostname==='127.0.0.1'||location.hostname==='creatarsh.onrender.com')?(location.origin+'/api'):'https://creatarsh.onrender.com/api')).replace(/\/$/,'');const TOKEN_KEY='creatarsh_customer_token';const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fallback={services:[{title:'Website Development',description:'High-performance business websites and modern digital experiences.'},{title:'Web Applications',description:'Scalable dashboards, portals and workflow-driven applications.'},{title:'Business Systems',description:'Custom systems that replace manual work and connect operations.'},{title:'E-commerce',description:'Conversion-focused stores with catalogues, orders and management.'},{title:'AI & Automation',description:'AI-powered workflows, assistants and intelligent automation.'},{title:'Custom Software',description:'Purpose-built digital products for unique requirements.'}],portfolio:[],testimonials:[],faqs:[]};
function token(){try{return localStorage.getItem(TOKEN_KEY)}catch{return null}}function customer(){try{return JSON.parse(localStorage.getItem('creatarsh_customer')||'null')}catch{return null}}
function saveCustomerSession(d){try{localStorage.setItem(TOKEN_KEY,d.token);localStorage.setItem('creatarsh_customer',JSON.stringify(d.customer));return true}catch{return false}}
function clearCustomerSession(){try{localStorage.removeItem(TOKEN_KEY);localStorage.removeItem('creatarsh_customer')}catch{}}
async function api(path,opt={}){const h={...(opt.headers||{})};const t=token();if(t)h.Authorization=`Bearer ${t}`;if(opt.body&&!h['Content-Type'])h['Content-Type']='application/json';const r=await fetch(API+path,{...opt,headers:h,cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.message||'Request failed');e.status=r.status;e.code=d.code;throw e}return d}
function nav(){const btn=$('#menuBtn');const nav=$('.site-nav');if(btn&&nav)btn.onclick=()=>nav.classList.toggle('open');document.querySelectorAll('.site-nav a').forEach(a=>a.onclick=()=>nav?.classList.remove('open'));}
function shell(active='home'){const c=customer();const navItems=[['services','Services'],['work','Work'],['about','About'],['contact','Contact']];const nav=$('.site-nav');if(nav)nav.innerHTML=navItems.map(([id,label])=>`<a class="${active===id?'active':''}" href="${id==='home'?'index.html':id+'.html'}">${label}</a>`).join('')+`<a class="account-link ${active==='account'?'active':''}" href="${c?'account.html':'login.html'}">${c?'My Account':'Client Login'} <span>↗</span></a>`;nav();if($('#year'))$('#year').textContent=new Date().getFullYear();}
function renderServices(items){const el=$('#servicesGrid');if(!el)return;el.innerHTML=items.map((x,i)=>`<article class="service-card"><div class="service-top"><span>${String(i+1).padStart(2,'0')}</span><b>${esc(x.icon||'✦')}</b></div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><div class="service-foot"><span>${esc(x.timeline||'Custom scope')}</span><span>↗</span></div></article>`).join('')}
function renderPortfolio(items){const el=$('#portfolioGrid');if(!el)return;el.innerHTML=items.length?items.map((x,i)=>{const m=x.media?.[0];return `<article class="project-card"><a href="work.html#${esc(x._id||'work')}" class="project-media" ${m?`style="background-image:linear-gradient(180deg,transparent,rgba(0,0,0,.55)),url('${esc(m)}')"`:''}><span>${esc(x.category||'PROJECT')}</span><b>${String(i+1).padStart(2,'0')}</b></a><div class="project-info"><div><h3>${esc(x.title)}</h3><p>${esc(x.description||'')}</p></div><div class="tags">${(x.technologies||[]).slice(0,4).map(t=>`<span>${esc(t)}</span>`).join('')}</div></div></article>`}).join(''):'<article class="project-card empty-project"><div class="project-media"><span>CREATARSH LAB</span><b>01</b></div><div class="project-info"><h3>Case studies are coming.</h3><p>We are building a portfolio of systems, products and digital experiences.</p></div></article>'}
function renderTestimonials(items){const el=$('#testimonialGrid');if(!el)return;el.innerHTML=items.length?items.map(x=>`<article><div class="stars">${'★'.repeat(Math.min(5,Math.max(1,x.rating||5)))}</div><blockquote>“${esc(x.quote)}”</blockquote><footer><b>${esc(x.name)}</b><span>${esc([x.role,x.company].filter(Boolean).join(' · '))}</span></footer></article>`).join(''):''}
function renderFaqs(items){const el=$('#faqList');if(!el)return;el.innerHTML=(items.length?items:[{question:'What does Creatarsh build?',answer:'Websites, web applications, mobile apps, e-commerce platforms, business systems and AI-powered workflows.'},{question:'How does a project start?',answer:'Send a project brief. We review the requirement, clarify scope and prepare the next steps.'},{question:'Can you build a complete business system?',answer:'Yes. We can design and develop custom systems around your actual business workflow.'}]).map(x=>`<details><summary>${esc(x.question)}<span>+</span></summary><p>${esc(x.answer)}</p></details>`).join('')}
async function loadContent(){try{const d=await api('/public/content');renderServices(d.services?.length?d.services:fallback.services);renderPortfolio(d.portfolio||[]);renderTestimonials(d.testimonials||[]);renderFaqs(d.faqs||[]);const s=d.site||{};if(s.heroTitle&&$('.hero-title'))$('.hero-title').textContent=s.heroTitle;if(s.heroText&&$('.hero-text'))$('.hero-text').textContent=s.heroText;if(s.announcement&&$('#announcement')){$('#announcement').textContent=s.announcement;$('#announcement').hidden=false}if(s.email&&$('#emailLink')){$('#emailLink').href='mailto:'+s.email;$('#emailLink').textContent=s.email}if(s.footerText&&$('#footerText'))$('#footerText').textContent=s.footerText}catch(e){renderServices(fallback.services);renderPortfolio([]);renderTestimonials([]);renderFaqs([])}}
function setupLeadForm(){const form=$('#leadForm');if(!form)return;const c=customer();if(c){for(const k of ['name','email','whatsapp','company']){const el=form.elements[k];if(el&&c[k])el.value=c[k]}}form.onsubmit=async e=>{e.preventDefault();const status=$('#formStatus'),button=form.querySelector('button');status.textContent='Sending…';button.disabled=true;try{const r=await api('/public/leads',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});status.textContent=`Project brief received · ${r.enquiryId}`;form.reset();if(c){form.elements.name.value=c.name;form.elements.email.value=c.email}}catch(err){status.textContent=err.message||'Could not submit right now.'}finally{button.disabled=false}}}
async function accountPage(){shell('account');const root=$('#accountRoot');if(!root)return;const c=customer();if(!c){root.innerHTML=`<section class="auth-wrap"><div class="auth-card"><div class="eyebrow">CREATARSH / CLIENT PORTAL</div><h1>Your projects.<br><em>One place.</em></h1><p>Sign in to view projects, quotations, invoices, payments and your account details.</p><div class="auth-tabs"><button class="active" data-auth="login">Sign in</button><button data-auth="register">Create account</button></div><form id="authForm"></form><p id="authStatus" class="form-status"></p></div></section>`;renderAuth('login');return}
root.innerHTML=`<section class="account-head"><div><div class="eyebrow">CLIENT PORTAL</div><h1>Welcome back, <em>${esc(c.name.split(' ')[0])}.</em></h1><p>Everything related to your Creatarsh projects, in one place.</p></div><button class="button ghost" id="logoutCustomer">Sign out</button></section><section class="account-grid"><article class="account-card highlight"><span>ACCOUNT</span><h3>${esc(c.name)}</h3><p>${esc(c.email)}</p><p>${esc(c.company||'Independent client')}</p><button class="text-link" id="editProfile">Edit profile ↗</button></article><article class="account-card"><span>PROJECTS</span><strong id="projectCount">—</strong><p>Active and completed work</p></article><article class="account-card"><span>QUOTATIONS</span><strong id="quoteCount">—</strong><p>Quotes available to review</p></article><article class="account-card"><span>PAYMENTS</span><strong id="paymentTotal">₹0</strong><p>Total recorded payments</p></article></section><section class="portal-section"><div class="portal-head"><div><div class="eyebrow">YOUR WORK</div><h2>Projects</h2></div><a class="button primary" href="contact.html">Start another project ↗</a></div><div id="projectList" class="portal-list"></div></section><section class="portal-section"><div class="portal-head"><div><div class="eyebrow">FINANCE</div><h2>Recent activity</h2></div></div><div id="paymentList" class="portal-list"></div></section>`;$('#logoutCustomer').onclick=()=>{clearCustomerSession();location.reload()};$('#editProfile').onclick=editProfile;try{const [p,q,pay]=await Promise.all([api('/customer/projects'),api('/customer/quotes'),api('/customer/payments')]);$('#projectCount').textContent=p.length;$('#quoteCount').textContent=q.length;$('#paymentTotal').textContent='₹'+pay.filter(x=>x.status==='SUCCESS').reduce((a,x)=>a+Number(x.amount||0),0).toLocaleString('en-IN');$('#projectList').innerHTML=p.length?p.map(x=>`<article class="portal-row"><div><span>${esc(x.status)}</span><h3>${esc(x.name)}</h3><p>${esc(x.description||'')}</p></div><div class="progress"><b>${x.progress||0}%</b><i><em style="width:${Math.min(100,Math.max(0,x.progress||0))}%"></em></i></div></article>`).join(''):'<div class="empty-portal">No projects yet. Your first project will appear here.</div>';$('#paymentList').innerHTML=pay.length?pay.slice(0,8).map(x=>`<article class="portal-row"><div><span>${esc(x.status)}</span><h3>${esc(x.project?.name||'Creatarsh project')}</h3><p>${x.paidAt?new Date(x.paidAt).toLocaleDateString():'Payment record'}</p></div><strong>₹${Number(x.amount||0).toLocaleString('en-IN')}</strong></article>`).join(''):'<div class="empty-portal">No payment activity yet.</div>'}catch(e){if(e.status===401){clearCustomerSession();location.reload()}}}
function renderAuth(mode){const form=$('#authForm');if(!form)return;form.innerHTML=mode==='login'?`<label>Email<input name="email" type="email" required placeholder="you@company.com"></label><label>Password<input name="password" type="password" required placeholder="••••••••"></label><button class="button primary full" type="submit">Sign in ↗</button>`:`<label>Name<input name="name" required placeholder="Your name"></label><label>Email<input name="email" type="email" required placeholder="you@company.com"></label><div class="field-row"><label>Phone<input name="phone" placeholder="+91"></label><label>Company<input name="company" placeholder="Company name"></label></div><label>Password<input name="password" type="password" minlength="8" required placeholder="Minimum 8 characters"></label><button class="button primary full" type="submit">Create account ↗</button>`;form.onsubmit=async e=>{e.preventDefault();const status=$('#authStatus'),button=form.querySelector('button[type=submit]');button.disabled=true;status.textContent='Please wait…';try{const d=await api('/customer/'+mode,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});if(!saveCustomerSession(d)){status.textContent='Your browser is blocking site storage. Please allow cookies/site storage to stay signed in.';return}location.href='account.html'}catch(err){status.textContent=err.message}finally{button.disabled=false}};document.querySelectorAll('[data-auth]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-auth]').forEach(x=>x.classList.toggle('active',x===b));renderAuth(b.dataset.auth)})}
async function editProfile(){const c=customer();const name=prompt('Name',c.name);if(name===null)return;const company=prompt('Company',c.company||'');const phone=prompt('Phone',c.phone||'');try{const d=await api('/customer/me',{method:'PUT',body:JSON.stringify({name,company,phone})});saveCustomerSession({token:token(),customer:{...c,...d.customer}});location.reload()}catch(e){alert(e.message)}}
async function authPage(mode){
  shell(mode==='login'?'login':'register');
  const root=$('#authPageRoot');
  if(!root)return;
  const c=customer();
  if(c && token()){ location.href='account.html'; return; }
  const isLogin=mode==='login';
  const existingForm=$('#authForm');
  if(!existingForm || !existingForm.children.length){
    root.innerHTML=`<section class="auth-wrap auth-page-wrap"><div class="auth-card auth-page-card"><div class="eyebrow">CREATARSH / CLIENT PORTAL</div><h1>${isLogin?'Welcome back.':'Create your client account.'}<br><em>${isLogin?'Your work, one place.':'Let’s build.'}</em></h1><p>${isLogin?'Sign in to access your projects, quotations, invoices, payments and account details.':'Create an account to track projects, receive quotations and manage your Creatarsh work.'}</p><div class="auth-tabs"><a class="${isLogin?'active':''}" href="login.html">Sign in</a><a class="${!isLogin?'active':''}" href="register.html">Create account</a></div><form id="authForm"></form><p id="authStatus" class="form-status"></p></div></section>`;
  }
  renderAuth(mode);
}
function pageInit(){const page=document.body.dataset.page||'home';shell(page);setupLeadForm();loadContent();if(page==='account')accountPage();if(page==='login'||page==='register')authPage(page);}
pageInit();
